name: Islamic Music Bot Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: music-bot

      - name: Install Multimedia Libraries via Conda
        shell: bash -l {0}
        run: |
          # Conda menginstal FFmpeg dan PyAV versi biner yang sudah jadi (Anti-Error Build)
          conda install -y -c conda-forge ffmpeg av pkg-config
          
      - name: Install AI Libraries
        shell: bash -l {0}
        run: |
          pip install torch torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install git+https://github.com/facebookresearch/audiocraft.git
          pip install pandas omegaconf hydra-core sentencepiece einops local-attention flashy trendy

      - name: Generate Music
        shell: bash -l {0}
        run: python generate_music.py

      - name: Commit and Push
        shell: bash -l {0}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          mkdir -p music
          git add music/*.mp3 || echo "No files"
          git commit -m "Add new original Islamic music" || echo "No changes"
          git push
